### ISSUE TITLE
1.2.1 error

### ISSUE THREAD

**Issue by nypisces** [jschneier/django-storages-redux#15]
File "/Users/NY/Envs/myproject/lib/python3.4/site-packages/storages/backends/s3boto.py", line 24, in <module>
    from storages.utils import setting
ImportError: cannot import name 'setting'

py3-storages work fine

**Comment by jschneier** [comment]
Hi and thanks for the report. Is there any more context to this exception? The test suites passes fine and I (and other people) are using this code in production and the path exists for that import so I'm having a hard time figuring out how that exception came about.

**Comment by jschneier** [comment]
Going to close this without further elaboration. To me it looks like you haven't properly installed the package. If not install via pip then running setup.py install in the repo should add the package to your PYTHONPATH.
